name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  flutter_bloc: ^8.1.3
  either_dart: ^1.0.0
  meta: ^1.10.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  string_validator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true
